name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      run: pip install uv

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest
      env:
        NAME: CI/CD World

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@flask-demo.emrecan.dev:flask-demo'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
